name: "Daikin MQTT connector"
description: "Allows to discover a Daikin Adapter BRP069A62 in the network and read and write its endpoints"
version: "1.0.11"
slug: "daikin-mqtt"
url: "https://github.com/jaakla/home-assistant-addons/daikin"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
startup: before
init: false
options:
  conf_file: "/config/daikin/pollingsettings.json"
schema:
  conf_file: str
  
